### ISSUE TITLE
(Phoenix.Router.NoRouteError) no route found for GET / (ConduitWeb.Router)

### ISSUE THREAD

**Issue by Yamilquery** [slashdotdash/conduit#15]
I follow the installation Readme.md, however I can't make it work, when I run `mix phx.server` I get the following:

```
➜  conduit git:(master) mix phx.server
warning: found quoted keyword "test" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
  mix.exs:59

[debug] Attempting to start Postgrex
[debug] Successfully started Postgrex (#PID<0.258.0>)
[debug] Attempting to start Postgrex.Notifications
[debug] Successfully started Postgrex.Notifications (#PID<0.267.0>)
[debug] Attempting to start Postgrex
[debug] Successfully started Postgrex (#PID<0.269.0>)
[info] Running ConduitWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[debug] Subscription "Accounts.Projectors.User"@"$all" subscribe to stream
[debug] Subscription "Blog.Projectors.Article"@"$all" subscribe to stream
[debug] Subscription "Blog.Projectors.Tag"@"$all" subscribe to stream
[debug] Subscription "Blog.Workflows.CreateAuthorFromUser"@"$all" subscribe to stream
[debug] Subscription "Accounts.Projectors.User"@"$all" subscribing to events
[debug] Subscription "Blog.Projectors.Article"@"$all" subscribing to events
[debug] Subscription "Blog.Workflows.CreateAuthorFromUser"@"$all" subscribing to events
[debug] Subscription "Accounts.Projectors.User"@"$all" requesting catch-up
[debug] Subscription "Blog.Projectors.Article"@"$all" requesting catch-up
[debug] Subscription "Blog.Projectors.Tag"@"$all" subscribing to events
[debug] Subscription "Blog.Workflows.CreateAuthorFromUser"@"$all" requesting catch-up
[debug] Subscription "Blog.Projectors.Tag"@"$all" requesting catch-up
[debug] Conduit.Accounts.Projectors.User has successfully subscribed to event store
[debug] Conduit.Blog.Projectors.Article has successfully subscribed to event store
[debug] Conduit.Blog.Workflows.CreateAuthorFromUser has successfully subscribed to event store
[debug] Conduit.Blog.Projectors.Tag has successfully subscribed to event store
```

And when I open http://localhost:4000, I get the next error:

```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET / (ConduitWeb.Router)
    (conduit) lib/conduit_web/router.ex:1: ConduitWeb.Router.__match_route__/4
    (conduit) lib/phoenix/router.ex:303: ConduitWeb.Router.call/2
    (conduit) lib/conduit_web/endpoint.ex:1: ConduitWeb.Endpoint.plug_builder_call/2
    (conduit) lib/plug/debugger.ex:102: ConduitWeb.Endpoint."call (overridable 3)"/2
    (conduit) lib/conduit_web/endpoint.ex:1: ConduitWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/yamildiazaguirre/Documents/grvty/conduit/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by Yamilquery** [comment]
Excuse me, I observed the router.ex file and found out that the main path for the API is not in the root.

Thank you!
